services:
  app:
    # Constrói a imagem a partir do Dockerfile no diretório atual
    build: .
    container_name: api
    ports:
      # Mapeia a porta 8000 do contêiner para a porta 8000 da sua máquina
      - "8000:8000"
    volumes:
      # Mapeia o diretório atual para o diretório /app dentro do contêiner.
      # Isso permite o live-reloading e salva o arquivo do SQLite na sua máquina.
      - .:/app
